language: node_js
node_js:
  - "5"
  - "4"
before_script:
  - "npm install"
after_success:
  - "npm install coveralls && cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  